name       : fritzing
version    : 0.9.6
release    : 9
source     :
    - https://github.com/fritzing/fritzing-app/archive/refs/tags/0.9.6.tar.gz : eb4ebe461c5d42edb4b10f1f824e7c855ad54555e222c5999061dead09834491
license    :
    - CC-BY-SA-3.0
    - GPL-3.0-or-later
component  : programming
summary    : Electronic design automation software
description: |
    The Fritzing application is an Electronic Design Automation software with a low entry barrier, suited for the needs of makers and hobbyists. It offers a unique real-life "breadboard" view, and a parts library with many commonly used high-level components. Fritzing makes it very easy to communicate about circuits, as well as to turn them into PCB layouts ready for production. It is particularly popular among Arduino and Raspberry Pi users, and is widely used in education and creative tinkering.
builddeps  :
    - pkgconfig(libgit2)
    - pkgconfig(Qt5SerialPort)
    - pkgconfig(Qt5Svg)
    - libboost-devel
    - quazip-devel
rundeps    :
    - fritzing-parts
setup      : |
    sed 's|LIBGIT_STATIC = true|LIBGIT_STATIC = false|' -i phoenix.pro
    %qmake DEFINES=QUAZIP_INSTALLED
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT="$installdir"
