name       : fritzing
version    : 0.9.3b
release    : 2
source     :
    - https://github.com/fritzing/fritzing-app/archive/0.9.3b.tar.gz : 7d92579cf87bbde2325e641b674b6c340fd27ee28a8ffe4c03e527e9a4307d88
license    :
    - CC-BY-SA-3.0
    - GPL-2.0
    - GPL-3.0
component  : programming
summary    : Electronic design automation software
description: |
    The Fritzing application is an Electronic Design Automation software with a low entry barrier, suited for the needs of makers and hobbyists. It offers a unique real-life "breadboard" view, and a parts library with many commonly used high-level components. Fritzing makes it very easy to communicate about circuits, as well as to turn them into PCB layouts ready for production. It is particularly popular among Arduino and Raspberry Pi users, and is widely used in education and creative tinkering.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libgit2)
    - pkgconfig(Qt5Core)
    - libboost-devel
rundeps    :
    - fritzing-parts
    - openjdk-8
setup      : |
    %patch -p1 < $pkgfiles/0001-Squashed-commit-of-the-following.patch
    mkdir -p $workdir/src/lib/boost_1_55_0
    ln -sf %libdir%/libboost* $workdir/src/lib/boost_1_55_0/
    qmake phoenix.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT="$installdir"
